version: '3.4'

services:
    db:
        image: postgres:9.6.10-alpine
        volumes:
            - dbdata:/var/lib/postgresql
        restart: always
        ports:
            - "55432:5432"
        environment:
            POSTGRES_USER: ksicht
            POSTGRES_PASS: ksicht
            POSTGRES_DB: ksicht

    website:
        build:
            context: .
        volumes:
            - ./ksicht:/ksicht/ksicht
        ports:
            - "8080:80"
        restart: always
        environment:
            DEBUG: 1
            DATABASE_DSN: postgresql://ksicht:ksicht@db:5432/ksicht
            ALLOWED_HOSTS: '*'

volumes:
    dbdata:
